### ISSUE TITLE
Toggle Switches

### ISSUE THREAD

**Issue by ffoodd** [shadeed/rtl-styling#11]
Hi there, me again <3

In [the (almost done!) RTL PR in Bootstrap](https://github.com/twbs/bootstrap/pull/30980), toggle switches got opposite reviews: after some researches [I managed to gather a few references and screenshots to reach a conclusion (comment in PR)](https://github.com/twbs/bootstrap/pull/30980#issuecomment-688205880) but since it's been quite discussed, I think it could be a good candidate for RTL Styling 101.

Moreover, do you agree with my conclusion that Toggle Switches should flip in RTL?

Thanks again for this awesome tool.

**Comment by shadeed** [comment]
Hello @ffoodd,

Thanks again for the continuous support and help for RTL Styling 101! That means a lot to me. I must admit that I'm a bit busy these days with my job and releasing the book. I hope that I will get some time soon for it as I have lots of ideas and updates to add.

Now to your question, I agree that toggle switches should be flipped in RTL. I did a quick research and found the following from [Firefox OS in Arabic](https://developer.mozilla.org/en-US/docs/Archive/B2G_OS/Firefox_OS_apps/Firefox_OS_in_Arabic)

![header-standard](https://user-images.githubusercontent.com/8038659/92402611-816ba700-f138-11ea-9636-66003387ec21.png)

So, yes, toggle switches should flip for RTL 😃

**Comment by ffoodd** [comment]
Thanks, keep going 😉

**Comment by shadeed** [comment]
I'm embarrassed that it's been over 3 years since this issue was created, but at least I closed it today. Thanks a lot for suggesting it. Fixed in the last commit.
