### ISSUE TITLE
The search icon shouldn't be flipped in the header case study

### ISSUE THREAD

**Issue by gorlanova** [shadeed/rtl-styling#32]
Hello Ahmad !

**First : thank you for this great guide about RTL, I'm building a component library and I'm the "front-end / a11y" dev of my team, so I try to learn as much as possible about accessibility to ensure what we build is for everyone, and your guide is fab !**

I noticed a tiny tiny visual discrepency : you explain in the section about icons that objects to manipulate should remain "right handed" and not be mirrored in RTL languages, but then in the website header section (at the very end) it appears mirrored in the LTR screenshot when showing both directions

<img width="736" alt="Screenshot 2023-11-24 at 22 56 34" src="https://github.com/shadeed/rtl-styling/assets/58045985/82e35255-f047-40e9-8e3b-a072487dd934">

I know it's a mistake because you displayed it correctly in the LRT-only screenshot before :)
That's it, 

Thanks again for all your work, I learn a lot from you !
Have a lovely day,

Nina

**Comment by shadeed** [comment]
Hello Nina,

Thanks a lot for the kind words, I'm glad that the guide is helpful. It means a lot! 🙏 

You're right, this is something that I overlooked. I just updated the guide and fixed it.

Thanks again,
