### ISSUE TITLE
text-decoration-skip-ink

### ISSUE THREAD

**Issue by notabene** [shadeed/rtl-styling#4]
Hi Shadeed,

Impressive genuine documentation here!

For [underline text decoration](https://www.rtlstyling.com/posts/rtl-styling/#2.1.-text-decoration) I was wondering if you had tested [text-decoration-skip-ink](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip-ink)?

It works well for Latin languages, so I was thinking maybe it's a good thing to add to your document. It's not supported everywhere yet but it's promising, but I don't know how well it behaves for Arabic below-word signs such as curves and dots.

**Comment by shadeed** [comment]
Hello @notabene , I just pushed an update for text-decoration. Your point was valid and it helped me to enhance the section. Thanks a lot 🙏Let me know please if all is good, so I can close this issue.

**Comment by notabene** [comment]
I considered it more as one solution among others than the only one but you're the boss! 😉

Glad I could help!
