### ISSUE TITLE
Email inputs with placeholder text

### ISSUE THREAD

**Issue by yuanworks** [shadeed/rtl-styling#6]
Hey there @shadeed, loved your guide on RTL! We've recently had a huge influx of Arabic-speaking users and your guide is incredibly useful. I wanted to ask if it's possible to add a section explaining how placeholder text for email/phone numbers should appear?

<img width="495" alt="image" src="https://user-images.githubusercontent.com/3508123/78671817-5de6cb00-7912-11ea-82d9-ba6dc76ed062.png">

Today I learned from your guide that phones/email should still be LTR, but I was wondering if, when inputting the email, but how should the placeholder text look like?

(Sorry if it's mentioned and I missed it). Thanks!

**Edit:** I noticed FB keeps the email input LTR when there is no placeholder text, but when there is placeholder text, it stays RTL. Is this correct?

**Comment by shadeed** [comment]
Hello @yuanworks, thank you for reading!

I'm not sure if I got your question correctly, the placeholder should be aligned the same as the email input while typing. Did you have a look at [this](https://www.rtlstyling.com/posts/rtl-styling/#form-inputs) section?

Let me know please if it's clear or in case I got the question incorrectly!

**Comment by yuanworks** [comment]
Thanks! I saw this section, sorry for not formulating the question correctly. But what if the placeholder text inside the text input for email is in Arabic (in your example it's mail@example.com), should it be LTR aligned?

```
[           arabic-placeholder-text]  (RTL)

when typing -->

[typing@myemail.com                ]  (LTR)
```

Should it work like this?

**Comment by shadeed** [comment]
Yes, your solution is 100% correct and logical for me. I will make sure to update the section asap with that regard. Thank you :)

**Comment by shadeed** [comment]
Hello @yuanworks, I updated the section with an example of the use-case you mentioned. Thank you :)

**Comment by yuanworks** [comment]
Great, thank you so much @shadeed!

**Comment by omar-dulaimi** [comment]
Hello,
Some nice work you have here and on the website.

Just wanted to check if it's possible to set rtl to a placeholder and ltr to an input field using just css, and have them change when typing

@shadeed
